version: '3'

services:
  caddy:
    image: tcharlezin/reverse-proxy:1.0.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == node-1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  site:
    image: tcharlezin/site:1.0.0
    deploy:
      mode: replicated
      replicas: 1

volumes:
  caddy_data:
    external: true
  caddy_config: